language: rust

rust:
  - stable
  - nightly

cache: cargo

before_install:
  - sudo apt-get install -y libarchive-dev

script:
  - cargo check --verbose --all

if: tag IS blank  # do not build tags, only commits

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always
