[package]
name = "rua"
version = "0.9.3"
description = "Secure jailed AUR helper for Arch Linux"
authors = ["Vasya Novikov <n1dr+cm3513git@ya.ru>"]
license="GPL-3.0-or-later"
keywords = ["archlinux", "aur", "build", "jail", "bubblewrap"]
readme = "README.md"
repository = "https://github.com/vn971/rua"
build = "build.rs"


[build-dependencies]
clap = "2.32.0"

[dependencies]
chrono = "0.4"
clap = "2.32.0"
directories = "1.0"
env_logger = "0.5.13"
fs2 = "0.4.3"
itertools = "0.7.8"
lazy_static = "1.1.0"
libalpm-fork = "0.1.3"
log = "0.4.6"
regex = "1"
tar = "0.4"
uname = "0.1.1"
xz2 = "0.1.6"



[profile.release]
lto = true
