[package]
name = "rua"
version = "0.11.2"
description = "Secure jailed AUR helper for Arch Linux"
authors = [
  "Vasili Novikov <n1dr+cm3513git@yandex.ru>",
  "Stefano Probst <senden9@gmail.com>",
]
license="GPL-3.0-or-later"
edition="2018"
keywords = ["archlinux", "aur", "build", "jail", "bubblewrap"]
readme = "README.md"
repository = "https://github.com/vn971/rua"
build = "build.rs"


[build-dependencies]
clap = "2.32.0"

[dependencies]
chrono = "0.4.6"
clap = "2.32.0"
directories = "1.0.2"
env_logger = "0.6.0"
fs2 = "0.4.3"
itertools = "0.8.0"
lazy_static = "1.2.0"
libalpm-fork = "0.1.4"
log = "0.4.6"
regex = "1.1.0"
rm_rf = "0.2.2"
tar = "0.4.20"
uname = "0.1.1"
users = "0.8.1"
xz2 = "0.1.6"


[profile.release]
lto = true
